from scriptcraft.layers.layer_1_tools.level_Z.asset_updater.asset_reconciliation.level_0.schema import (
    ASSET_RAW_TAG,
    ASSET_RAW_EMP_ID,
    ASSET_RAW_LOCATION,
    ASSET_RAW_CUSTODIAN,
    ASSET_RAW_DESCRIPTION,
    FORM_RAW_TAG,
    FORM_RAW_EMP_ID,
    FORM_RAW_LOCATION,
    FORM_NORMALIZED_EMPLOYEE_NAME,
    MERGED_ASSET_EMP_ID,
    MERGED_ASSET_LOCATION,
    MERGED_ASSET_CUSTODIAN,
    MERGED_ASSET_DESCRIPTION,
    MERGED_FORM_EMP_ID,
    MERGED_FORM_EMPLOYEE_NAME,
    MERGED_FORM_LOCATION,
)

# ----------------------------
# REQUIRED INPUT CONTRACTS
# ----------------------------

ASSET_REQUIRED_COLUMNS = [
    ASSET_RAW_TAG,
    ASSET_RAW_EMP_ID,
    ASSET_RAW_LOCATION,
    ASSET_RAW_CUSTODIAN,
    ASSET_RAW_DESCRIPTION,
]

FORM_REQUIRED_COLUMNS = [
    FORM_RAW_TAG,
    FORM_RAW_EMP_ID,
    FORM_RAW_LOCATION,
    FORM_NORMALIZED_EMPLOYEE_NAME,
]


# ----------------------------
# RENAME MAPS (DRY FIX)
# ----------------------------

ASSET_TO_MERGED_MAP = {
    ASSET_RAW_EMP_ID: MERGED_ASSET_EMP_ID,
    ASSET_RAW_LOCATION: MERGED_ASSET_LOCATION,
    ASSET_RAW_CUSTODIAN: MERGED_ASSET_CUSTODIAN,
    ASSET_RAW_DESCRIPTION: MERGED_ASSET_DESCRIPTION,
}

FORM_TO_MERGED_MAP = {
    FORM_RAW_EMP_ID: MERGED_FORM_EMP_ID,
    FORM_RAW_LOCATION: MERGED_FORM_LOCATION,
    FORM_NORMALIZED_EMPLOYEE_NAME: MERGED_FORM_EMPLOYEE_NAME,
}